// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvvxstgtkiovkqmbnzyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2dnhzdGd0a2lvdmtxbWJuenl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NzE1MTAsImV4cCI6MjA3MDM0NzUxMH0.dVbwBUXHq7RIBC7Mj1QUCEoorG3ivCx3l9A27Jli7-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});